import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => {
  const img = PlaceHolderImages.find(p => p.id === id);
  if (!img) {
    return { url: 'https://placehold.co/600/800', alt: 'Placeholder', hint: 'placeholder' };
  }
  return { url: img.imageUrl, alt: img.description, hint: img.imageHint };
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'ethereal-trench-coat',
    name: 'Ethereal Trench Coat',
    description: 'A timeless silhouette reimagined with an iridescent, water-resistant fabric.',
    price: 450,
    category: 'women',
    style: 'formal',
    images: [
      { ...findImage('ethereal-trench-main'), colorName: 'Beige' },
      { ...findImage('ethereal-trench-side'), colorName: 'Gray' },
      { ...findImage('urban-nomad-1'), colorName: 'Black'},
    ],
    availableColors: [
      { name: 'Beige', hex: '#f6eada' },
      { name: 'Gray', hex: '#9ca3af' },
      { name: 'Black', hex: '#111827' },
    ]
  },
  {
    id: '2',
    slug: 'urban-nomad-jacket',
    name: 'Urban Nomad Jacket',
    description: 'A versatile jacket designed for the modern explorer.',
    price: 280,
    category: 'men',
    style: 'streetwear',
    images: [findImage('urban-nomad-1')],
  },
  {
    id: '3',
    slug: 'silk-flow-blouse',
    name: 'Silk-Flow Blouse',
    description: 'A fluid blouse made from pure mulberry silk.',
    price: 190,
    category: 'women',
    style: 'casual',
    images: [findImage('silk-blouse-1')],
  },
  {
    id: '4',
    slug: 'tailored-linen-trousers',
    name: 'Tailored Linen Trousers',
    description: 'Expertly tailored from fine Italian linen.',
    price: 220,
    category: 'men',
    style: 'formal',
    images: [findImage('linen-trousers-1')],
  },
  {
    id: '5',
    slug: 'classic-leather-tote',
    name: 'Classic Leather Tote',
    description: 'A spacious and elegant tote bag crafted from genuine leather.',
    price: 320,
    category: 'bags',
    images: [findImage('leather-tote')],
  },
  {
    id: '6',
    slug: 'everyday-canvas-backpack',
    name: 'Everyday Canvas Backpack',
    description: 'A durable and stylish backpack for your daily adventures.',
    price: 150,
    category: 'bags',
    images: [findImage('canvas-backpack')],
  },
  {
    id: '7',
    slug: 'cozy-kids-hoodie',
    name: 'Cozy Kids Hoodie',
    description: 'A warm and comfortable hoodie for children.',
    price: 80,
    category: 'children',
    style: 'casual',
    images: [findImage('kids-hoodie')],
  },
  {
    id: '8',
    slug: 'stylish-crossbody-bag',
    name: 'Stylish Crossbody Bag',
    description: 'A compact and chic crossbody bag for any occasion.',
    price: 180,
    category: 'bags',
    images: [findImage('stylish-crossbody-bag')],
  },
  {
    id: '9',
    slug: 'leather-duffle-bag',
    name: 'Leather Duffle Bag',
    description: 'A spacious and sophisticated leather duffle for weekend getaways.',
    price: 350,
    category: 'bags',
    images: [findImage('leather-duffle-bag')],
  },
  {
    id: '10',
    slug: 'minimalist-clutch',
    name: 'Minimalist Clutch',
    description: 'An elegant and minimalist clutch for evenings out.',
    price: 120,
    category: 'bags',
    images: [findImage('minimalist-clutch')],
  },
  {
    id: '11',
    slug: 'cucinelli-shirt-men',
    name: 'Cucinelli Shirt',
    description: 'High-thread-count poplin cotton with a stiffened Italian collar.',
    price: 180,
    category: 'men',
    style: 'formal',
    images: [findImage('men-formal-shirt')],
  },
  {
    id: '12',
    slug: 'simoni-suit-men',
    name: 'Simoni 2-Piece Suit',
    description: 'Wool-blend fabric with a slim lapel and reinforced shoulder structure.',
    price: 750,
    category: 'men',
    style: 'formal',
    images: [findImage('men-formal-suit')],
  },
  {
    id: '13',
    slug: 'graphic-hoodie-men',
    name: 'Graphic Hoodie',
    description: 'French terry fabric with high-density screen printing on the chest.',
    price: 120,
    category: 'men',
    style: 'streetwear',
    images: [findImage('men-street-hoodie')],
  },
  {
    id: '14',
    slug: 'carducci-polo-men',
    name: 'Carducci Polo',
    description: 'Piqué knit cotton with a ribbed collar and mother-of-pearl buttons.',
    price: 85,
    category: 'men',
    style: 'casual',
    images: [findImage('men-casual-polo')],
  },
  {
    id: '15',
    slug: 'checked-blazer-men',
    name: 'Checked Blazer',
    description: 'Heavy wool tweed with a vintage plaid pattern and notched lapels.',
    price: 320,
    category: 'men',
    style: 'vintage',
    images: [findImage('men-vintage-blazer')],
  },
  {
    id: '16',
    slug: 'prada-tee-men',
    name: 'Prada Basic Tee',
    description: 'Fine-gauge mercerized cotton with a seamless neck and slim fit.',
    price: 95,
    category: 'men',
    style: 'minimal',
    images: [findImage('men-minimal-tee')],
  },
  {
    id: '17',
    slug: 'zamra-blazer-women',
    name: 'Zamra Blazer',
    description: 'Tailored wool-blend blazer with satin lining and gold button accents.',
    price: 420,
    category: 'women',
    style: 'formal',
    images: [findImage('women-formal-blazer')],
  },
  {
    id: '18',
    slug: 'flared-jeans-women',
    name: 'Flared Jeans',
    description: 'High-rise denim with a wide flare and raw-edge hem for a retro look.',
    price: 130,
    category: 'women',
    style: 'streetwear',
    images: [findImage('women-street-jeans')],
  },
  {
    id: '19',
    slug: 'rosso-top-women',
    name: 'Rosso Top',
    description: 'Soft-touch viscose jersey with a relaxed drape and scooped neck.',
    price: 65,
    category: 'women',
    style: 'casual',
    images: [findImage('women-casual-top')],
  },
  {
    id: '20',
    slug: 'chinese-dress-women',
    name: 'Chinese Dress',
    description: 'Silk-jacquard fabric with a mandarin collar and traditional knot buttons.',
    price: 250,
    category: 'women',
    style: 'vintage',
    images: [findImage('women-vintage-dress')],
  },
  {
    id: '21',
    slug: 'catania-top-women',
    name: 'Catania Top',
    description: 'Minimalist cotton-silk blend tank with clean heat-sealed hems.',
    price: 75,
    category: 'women',
    style: 'minimal',
    images: [findImage('women-minimal-top')],
  },
  {
    id: '22',
    slug: 'ngr-hoodie-unisex',
    name: 'NGR Hoodie',
    description: 'Oversized fleece-lined hoodie with a heavy-duty kangaroo pocket.',
    price: 150,
    category: 'children',
    style: 'streetwear',
    images: [findImage('unisex-street-hoodie')],
  },
  {
    id: '23',
    slug: 'trench-coat-unisex',
    name: 'Trench Coat',
    description: 'Heavyweight gabardine with a double-breasted front and waist belt.',
    price: 380,
    category: 'children',
    style: 'formal',
    images: [findImage('unisex-formal-trench')],
  },
  {
    id: '24',
    slug: 'erynight-sweater-unisex',
    name: 'Erynight Sweater',
    description: 'Soft-knit acrylic sweater with a classic crew neck and ribbed trim.',
    price: 110,
    category: 'children',
    style: 'casual',
    images: [findImage('unisex-casual-sweater')],
  },
  {
    id: '25',
    slug: 'grandpa-sweater-unisex',
    name: 'Grandpa Sweater',
    description: 'Vintage-style cable knit with an oversized fit and shawl collar.',
    price: 140,
    category: 'children',
    style: 'vintage',
    images: [findImage('unisex-vintage-sweater')],
  },
  {
    id: '26',
    slug: 'miray-tshirt-unisex',
    name: 'Miray T-shirt',
    description: 'Ultra-soft bamboo cotton blend with a clean, straight-cut hem.',
    price: 50,
    category: 'children',
    style: 'minimal',
    images: [findImage('unisex-minimal-tee')],
  }
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug);
};

export const getProductsByCategory = (category: 'women' | 'men' | 'children' | 'bags'): Product[] => {
  return products.filter(p => p.category === category);
}
