import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => {
  const img = PlaceHolderImages.find(p => p.id === id);
  if (!img) {
    return { url: 'https://placehold.co/600/800', alt: 'Placeholder', hint: 'placeholder' };
  }
  return { url: img.imageUrl, alt: img.description, hint: img.imageHint };
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'ethereal-trench-coat',
    name: 'Ethereal Trench Coat',
    description: 'A timeless silhouette reimagined with an iridescent, water-resistant fabric.',
    price: 450,
    category: 'women',
    images: [
      findImage('ethereal-trench-main'),
      findImage('ethereal-trench-side'),
    ],
  },
  {
    id: '2',
    slug: 'urban-nomad-jacket',
    name: 'Urban Nomad Jacket',
    description: 'A versatile jacket designed for the modern explorer.',
    price: 280,
    category: 'men',
    images: [findImage('urban-nomad-1')],
  },
  {
    id: '3',
    slug: 'silk-flow-blouse',
    name: 'Silk-Flow Blouse',
    description: 'A fluid blouse made from pure mulberry silk.',
    price: 190,
    category: 'women',
    images: [findImage('silk-blouse-1')],
  },
  {
    id: '4',
    slug: 'tailored-linen-trousers',
    name: 'Tailored Linen Trousers',
    description: 'Expertly tailored from fine Italian linen.',
    price: 220,
    category: 'men',
    images: [findImage('linen-trousers-1')],
  },
  {
    id: '5',
    slug: 'classic-leather-tote',
    name: 'Classic Leather Tote',
    description: 'A spacious and elegant tote bag crafted from genuine leather.',
    price: 320,
    category: 'bags',
    images: [findImage('leather-tote')],
  },
  {
    id: '6',
    slug: 'everyday-canvas-backpack',
    name: 'Everyday Canvas Backpack',
    description: 'A durable and stylish backpack for your daily adventures.',
    price: 150,
    category: 'bags',
    images: [findImage('canvas-backpack')],
  },
  {
    id: '7',
    slug: 'cozy-kids-hoodie',
    name: 'Cozy Kids Hoodie',
    description: 'A warm and comfortable hoodie for children.',
    price: 80,
    category: 'children',
    images: [findImage('kids-hoodie')],
  },
  {
    id: '8',
    slug: 'stylish-crossbody-bag',
    name: 'Stylish Crossbody Bag',
    description: 'A compact and chic crossbody bag for any occasion.',
    price: 180,
    category: 'bags',
    images: [findImage('stylish-crossbody-bag')],
  },
  {
    id: '9',
    slug: 'leather-duffle-bag',
    name: 'Leather Duffle Bag',
    description: 'A spacious and sophisticated leather duffle for weekend getaways.',
    price: 350,
    category: 'bags',
    images: [findImage('leather-duffle-bag')],
  },
  {
    id: '10',
    slug: 'minimalist-clutch',
    name: 'Minimalist Clutch',
    description: 'An elegant and minimalist clutch for evenings out.',
    price: 120,
    category: 'bags',
    images: [findImage('minimalist-clutch')],
  },
  {
    id: '11',
    slug: 'cucinelli-shirt',
    name: 'Cucinelli Shirt',
    description: 'High-thread-count poplin cotton with a stiffened Italian collar.',
    price: 250,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '12',
    slug: 'simoni-2-piece-suit',
    name: 'Simoni 2-Piece Suit',
    description: 'Wool-blend fabric with a slim lapel and reinforced shoulder structure.',
    price: 750,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '13',
    slug: 'ngr-sportline-tee',
    name: 'NGR Sportline Tee',
    description: 'Heavyweight 240gsm cotton with a dropped shoulder and boxy fit.',
    price: 90,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '14',
    slug: 'graphic-hoodie',
    name: 'Graphic Hoodie',
    description: 'French terry fabric with high-density screen printing on the chest.',
    price: 130,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '15',
    slug: 'carducci-polo',
    name: 'Carducci Polo',
    description: 'Piqué knit cotton with a ribbed collar and mother-of-pearl buttons.',
    price: 110,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '16',
    slug: 'zamra-blazer',
    name: 'Zamra Blazer',
    description: 'Tailored wool-blend blazer with satin lining and gold button accents.',
    price: 320,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '17',
    slug: 'molina-pants',
    name: 'Molina Pants',
    description: 'High-waisted official trousers made from non-crease crepe fabric.',
    price: 180,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '18',
    slug: 'flared-jeans',
    name: 'Flared Jeans',
    description: 'High-rise denim with a wide flare and raw-edge hem for a retro look.',
    price: 150,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '19',
    slug: 'ankara-kimono',
    name: 'Ankara Kimono',
    description: 'Authentic wax print cotton with vibrant colors and an open-front.',
    price: 210,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '20',
    slug: 'rosso-top',
    name: 'Rosso Top',
    description: 'Soft-touch viscose jersey with a relaxed drape and scooped neck.',
    price: 85,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '21',
    slug: 'ngr-hoodie',
    name: 'NGR Hoodie',
    description: 'Oversized fleece-lined hoodie with a heavy-duty kangaroo pocket.',
    price: 95,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '22',
    slug: 'fashion-cap',
    name: 'Fashion Cap',
    description: '6-panel canvas cap with an adjustable brass slider and curved brim.',
    price: 45,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '23',
    slug: 'trench-coat',
    name: 'Trench Coat',
    description: 'Heavyweight gabardine with a double-breasted front and waist belt.',
    price: 280,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '24',
    slug: 'erynight-sweater',
    name: 'Erynight Sweater',
    description: 'Soft-knit acrylic sweater with a classic crew neck and ribbed trim.',
    price: 115,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '25',
    slug: 'grandpa-sweater',
    name: 'Grandpa Sweater',
    description: 'Vintage-style cable knit with an oversized fit and shawl collar.',
    price: 125,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '26',
    slug: 'dorelli-official-shirt',
    name: 'Dorelli Official',
    description: 'A tailored-fit shirt made from breathable, easy-iron broadcloth cotton.',
    price: 180,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '27',
    slug: 'cargo-joggers',
    name: 'Cargo Joggers',
    description: 'Rugged twill with 6 tactical pockets and elasticated bungee cuffs.',
    price: 130,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '28',
    slug: 'standard-jeans',
    name: 'Standard Jeans',
    description: 'Classic 5-pocket denim with reinforced rivets and a straight-leg cut.',
    price: 160,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '29',
    slug: 'sweater-vest',
    name: 'Sweater Vest',
    description: 'Cable-knit lambswool blend with a V-neck and ribbed armholes.',
    price: 90,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '30',
    slug: 'leather-belt',
    name: 'Leather Belt',
    description: 'Single-piece full-grain leather with a brushed stainless steel buckle.',
    price: 60,
    category: 'men',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '31',
    slug: 'skirt-suit',
    name: 'Skirt Suit',
    description: 'Professional matching set featuring a pencil skirt and cropped jacket.',
    price: 420,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '32',
    slug: 'ankara-mini-top',
    name: 'Ankara Mini Top',
    description: 'Cropped corset-style top made from structured African print fabric.',
    price: 95,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '33',
    slug: 'denim-dress',
    name: 'Denim Dress',
    description: 'Mid-weight denim shirt-dress with a tie-waist and brass buttons.',
    price: 175,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '34',
    slug: 'midi-skirt',
    name: 'Midi Skirt',
    description: 'High-waist pleated skirt made from a heavy satin fabric.',
    price: 140,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '35',
    slug: 'knit-cardigan',
    name: 'Knit Cardigan',
    description: 'Fine-gauge merino wool with a simple hidden button placket.',
    price: 160,
    category: 'women',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '36',
    slug: 'utility-vest',
    name: 'Utility Vest',
    description: 'Multi-pocket "techwear" vest made from durable ripstop nylon.',
    price: 110,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '37',
    slug: 'pima-cotton-shirt',
    name: 'Pima Cotton Shirt',
    description: 'Minimalist button-up with no collar for a modern formal look.',
    price: 85,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '38',
    slug: 'flannel-shirt',
    name: 'Flannel Shirt',
    description: 'Brushed cotton flannel with a classic plaid print and twin pockets.',
    price: 70,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '39',
    slug: 'newsboy-cap',
    name: 'Newsboy Cap',
    description: 'Traditional 8-panel wool blend cap with a button top.',
    price: 40,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
  {
    id: '40',
    slug: 'white-sneakers',
    name: 'White Sneakers',
    description: 'Simple low-profile leather sneakers with hidden stitching.',
    price: 120,
    category: 'children',
    images: [findImage('generic-apparel-1')],
  },
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug);
};

export const getProductsByCategory = (category: 'women' | 'men' | 'children' | 'bags'): Product[] => {
  return products.filter(p => p.category === category);
}

    