import type { Metadata } from "next";
import { PT_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "@/components/ui/toaster";
import WhatsAppChannelModal from "@/components/layout/WhatsAppChannelModal";
import { FirebaseClientProvider } from "@/firebase";
import { cn } from "@/lib/utils";

const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-pt-sans",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Nextgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-gray-50 font-sans",
          ptSans.variable,
          playfairDisplay.variable
        )}
      >
        <AppProvider>
          <FirebaseClientProvider>
            <div className="min-h-screen flex flex-col">
              <Header />
              <main className="max-w-7xl mx-auto px-4 pb-4 pt-8 md:px-6 md:pb-6 md:pt-10 w-full flex-grow">
                {children}
              </main>
              <Footer />
            </div>
            <Toaster />
            <WhatsAppChannelModal />
          </FirebaseClientProvider>
        </AppProvider>
      </body>
    </html>
  );
}
