import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "@/components/ui/toaster";
import WhatsAppChannelModal from "@/components/layout/WhatsAppChannelModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <AppProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="max-w-7xl mx-auto p-4 md:p-6 w-full flex-grow">
              {children}
            </main>
            <Footer />
          </div>
          <Toaster />
          <WhatsAppChannelModal />
        </AppProvider>
      </body>
    </html>
  );
}
